apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-allow-dns-access
spec:
  rules:
  - generate:
      data:
        spec:
          egress:
          - ports:
            - port: 53
              protocol: UDP
            - port: 53
              protocol: TCP
            to:
            - namespaceSelector:
                matchLabels:
                  name: kube-system
          - ports:
            - port: 53
              protocol: UDP
            - protocol: TCP
            to: null
          podSelector:
            matchLabels: {}
          policyTypes:
          - Egress
      kind: NetworkPolicy
      name: allow-dns-access
      namespace: '"{{"request.object.metadata.name"}}"'
      synchronize: false
    match:
      resources:
        kinds:
        - Namespace
    name: default-allow-dns-access
  validationFailureAction: audit
